lms/lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import handler404, url
import debug_toolbar
from django.urls import include, path
from students.views import IndexPage, RegistrationStudent


handler404 = 'students.views.page_error.view_404'

urlpatterns = [
    path("", IndexPage.as_view(), name="hello"),
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("registration/", RegistrationStudent.as_view(), name="registration"),
    path('oauth/', include('social_django.urls'), name='social'),
    path('django_tools/', include('admin_tools.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lms/students/urls.py
from students.views.students_views import (CreateStudent, IndexPage, GetStudent, UpdateStudent,
                            DeleteStudent, LoginStudent, LogoutStudent, ActivateUser, RegistrationStudent)
from django.urls import path


app_name = "students"

urlpatterns = [
    path("hello/", IndexPage.as_view(), name="hello"),
    path("list/", GetStudent.as_view(), name="list"),
    path("create/", CreateStudent.as_view(), name="create"),
    path("update/<int:pk>/", UpdateStudent.as_view(), name="update"),
    path("delete/<int:pk>/", DeleteStudent.as_view(), name="delete"),
    path("login", LoginStudent.as_view(), name="login"),
    path("logout", LogoutStudent.as_view(), name="logout"),
    path("logout", LogoutStudent.as_view(), name="logout"),
    path("registration/", RegistrationStudent.as_view(), name="registration"),
    path('activate/<str:uidb64>/<str:token>', ActivateUser.as_view(),
         name='activate')
]

lms/teachers/urls.py
from teachers.views import GetTeacher, CreateTeacher
from django.urls import path


app_name = "teachers"

urlpatterns = [
    path("list/", GetTeacher.as_view(), name="list"),
    path("create/", CreateTeacher.as_view(), name="create"),
]

lms/students/models.py
import uuid
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.core.validators import MinLengthValidator
from django.db import models
import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver
from faker import Faker
from students.validators import no_elon_validator
from courses.models import Course, UserType
from django.contrib.auth.models import User, PermissionsMixin, AbstractBaseUser
from django.utils.translation import ugettext as _
from students.managers import CustomUserManager, PeopleManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    photo = models.ImageField(upload_to='user_photos/', null=True, blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )

    objects = CustomUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class ExtendedUser(CustomUser):
    people = PeopleManager()

    class Meta:
        proxy = True
        ordering = ('first_name',)

    def some_action(self):
        print(self.username)


class Person(models.Model):

    first_name = models.CharField(
        max_length=60, null=False, validators=[MinLengthValidator(2)]
    )
    last_name = models.CharField(
        max_length=80, null=False, validators=[MinLengthValidator(2)]
    )
    email = models.EmailField(
        max_length=120, null=True, validators=[no_elon_validator], unique=True
    )
    birthdate = models.DateField(null=True, default=datetime.date.today)

    avatar_image = models.ImageField(upload_to='static/', null=True, blank=True)

    summary = models.FileField(upload_to='static/', null=True, blank=True)

    class Meta:
        abstract = True


class Student(Person):

    course = models.ForeignKey(Course, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.full_name()}, {self.age()}, {self.email} id({self.id})"

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def age(self):
        return datetime.datetime.now().year - self.birthdate.year

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for _ in range(count):
            st = cls(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birthdate=faker.date_time_between(start_date="-30y", end_date="-18y"),
            )
            st.save()


class UserProfile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    birthdate = models.DateField(blank=True, null=True)
    avatar_image = models.ImageField(upload_to='static/', null=True, blank=True)
    summary = models.FileField(upload_to='static/', null=True, blank=True)
    type = models.ForeignKey(UserType, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"


@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

lms/students/forms.py
from django import forms
from django.forms import ModelForm, DateInput, EmailField
from django.core.exceptions import ValidationError
from students.models import Student
import datetime
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationStudentForm(UserCreationForm):
    email = EmailField(max_length=200,
                       help_text="Registration without email is not possible!")

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class StudentCreateForm(ModelForm):
    class Meta:
        model = Student
        fields = [
            "first_name",
            "last_name",
            "email",
            "birthdate",
            "course",
            "avatar_image",
            "summary"
        ]
        birthdate = {"birthdate": DateInput()}

    def clean_birthdate(self):
        birthdate = self.cleaned_data["birthdate"]
        user_age = datetime.date.today() - birthdate
        how_old_student = user_age.days // 365
        if how_old_student < 18:
            raise ValidationError(f"the user must only users who are 18 or older")
        return birthdate

    def clean_email(self):
        no_valid_email = ["@xyz.com", "@xzy.com", "@zyx.com"]
        email = self.cleaned_data["email"]
        val_answer = [i for i in no_valid_email if i in email]
        if val_answer != []:
            raise ValidationError(f"Email {val_answer[0]} banned")
        email = self.cleaned_data["email"].strip()
        if Student.objects.filter(email__iexact=email).exists():
            raise ValidationError(f"Student with this Email({email}) already exists")
        return email

    def clean(self):
        cleaned_data = super().clean()

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]
        if first_name == last_name:
            raise ValidationError("First and last names can't be equal")

        return cleaned_data

    @staticmethod
    def normalize_name(name):
        return name.lower().strip().capitalize()

    def clean_first_name(self):
        first_name = self.cleaned_data["first_name"]

        return self.normalize_name(first_name)

    def clean_last_name(self):
        last_name = self.cleaned_data["last_name"]

        return self.normalize_name(last_name)


class StudentGetForm(ModelForm):
    class Meta:
        pass


class StudentUpdateForm(StudentCreateForm):
    class Meta(StudentCreateForm.Meta):
        fields = ["avatar_image", "first_name", "last_name", "birthdate", "course", "summary"]

lms/students/views/page_error.py
from django.shortcuts import render


def view_404(request, exception):
    return render(request, "404.html")

lms/students/views/students_views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.core.mail import EmailMessage
from django.forms.utils import ErrorList
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode
from django.views.generic import CreateView, TemplateView, UpdateView, DeleteView, RedirectView
from students.models import Student
from courses.models import Course
from students.forms import RegistrationStudentForm
from students.services.emails import send_registration_email
from students.token_generator import TokenGenerator


class IndexPage(TemplateView):
    template_name = "index.html"


class GetStudent(TemplateView):
    model = Student
    template_name = "students_table.html"
    success_url = reverse_lazy("students:list")

    def get(self, request, *args, **kwargs):
        course = Course.objects.all()
        if request.GET.get('featured'):
            selected_course = Course.objects.get(name=request.GET.get('featured')).id
            students = Student.objects.filter(course=selected_course)
            context = {
                "students": students,
                "courses": course,
                "selected_course": selected_course
            }
        else:
            students = Student.objects.all().order_by("id")
            context = {
                "students": students,
                "courses": course
            }

        return render(request, 'students_table.html', context)


class CreateStudent(LoginRequiredMixin, CreateView):
        template_name = "students_create.html"
        fields = "__all__"
        model = Student
        initial = {
            "first_name": "default",
            "last_name": "default",
        }
        success_url = reverse_lazy("students:list")

        def form_valid(self, form):
            self.object = form.save(commit=False)
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            if first_name == last_name:
                form._errors["first_name"] = ErrorList(["dsadas"])
                form._errors["last_name"] = ErrorList(
                    [u"You already have an email with that name man."])
                return super().form_invalid(form)
            return super().form_valid(form)


class UpdateStudent(LoginRequiredMixin, UpdateView):
    model = Student
    template_name = "students_update.html"
    fields = "__all__"
    success_url = reverse_lazy("students:list")


class DeleteStudent(LoginRequiredMixin, DeleteView):
    model = Student
    template_name = "student_delete.html"
    success_url = reverse_lazy("students:list")


class LoginStudent(LoginView):
    pass


class LogoutStudent(LogoutView):
    template_name = "index.html"


class RegistrationStudent(CreateView):
    form_class = RegistrationStudentForm
    template_name = "registration/registration.html"
    success_url = reverse_lazy("students:hello")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_active = False
        self.object.save()
        send_registration_email(request=self.request,
                                user_instance=self.object)
        return super().form_valid(form)


class ActivateUser(RedirectView):
    url = reverse_lazy('students:list')

    def get(self, request, uidb64, token, *args, **kwargs):
        print(f"uidb64: {uidb64}")
        print(f"token: {token}")

        try:
            user_pk = force_bytes(urlsafe_base64_decode(uidb64))
            print(f"user_pk: {user_pk}")
            current_user = User.objects.get(pk=user_pk)
        except (User.DoesNotExist, ValueError, TypeError):
            return HttpResponse("Wrong data")

        if current_user and TokenGenerator().check_token(current_user, token):
            current_user.is_active = True
            current_user.save()

            login(request, current_user)
            return super().get(request, *args, **kwargs)
        return HttpResponse("Wrong data")

lms/students/templates/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %} Home  {% endblock %}</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Навигация</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

        <a class="navbar-brand" href="{% url 'students:hello' %}">Home</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Student<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'students:list' %}">All students table</a></li>
                  {% if user.is_authenticated %}


                <li><a href="{% url 'students:create' %}">Create New Student</a></li>
                  {% endif %}
              </ul>
          </li>

        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Teacher<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'teachers:list' %}">All teachers table</a></li>
                {% if user.is_authenticated %}
              <li><a href="{% url 'teachers:create' %}">Teachers create</a></li>
                {% endif %}
            </ul>
          </li>
            
            {% if user.is_authenticated %}
                    
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'students:logout' %}">{{ user.username }} || Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'students:login' %}"> Login</a>
                    </li>

                     <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration' %}">Registration</a>
                    </li>
                {% endif %}
        </ul>

      </div>

  </nav>

<main class="container">
  <div class="bg-light p-5 rounded">

      {% block content %}
        <h1>Home page</h1>
                    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                      Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                      Excepteur sint occaecat cupidatat non proident,
                      sunt in culpa qui officia deserunt mollit anim id est laborum</p>

      {% endblock %}
  </div>
</main>
  <!-- jQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

lms/students/templates/student_delete.html
{% extends 'index.html' %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">
        {% csrf_token %}
      <p>Are you sure you want to delete "{{ student.first_name }} {{ student.last_name }}"?</p>
      <input type="submit"  class="btn btn-danger" value="Confirm" />
    </form>
{% endblock content %}

lms/students/templates/students_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <br>
            <input class="btn btn-info" type="submit" value="Create"/>
        </form>
    </div>
{% endblock %}

lms/students/templates/students_table.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block title %} Students {% endblock  %}

{% block content %}
    <form  method="get">
    <label for="featured">Courses</label>
    <select name="featured">
        {% for course in courses %}
        <option value= {{ course.name }} />{{ course.name }}</option>
        {% endfor %}
        <option value="" />All students</option>
    </select>
     <input class="btn btn-info" type="submit" value="Filter"/>
    </form>

    <table class="table table-dark table-hover">
        <thead>
        <tr>

        </tr>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Avatar</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Birthdate</th>
            <th scope="col">Age</th>
            <th scope="col">Course</th>

        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>

                <th scope="row">{{ student.id }}</th>
                <td>
                    {% if student.avatar_image %}
                    <img src="{{ student.avatar_image.url }}" width="70" height="80" >
                    {% endif %}
                </td>
                <td>{{ student.first_name }}</td>

                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.birthdate }}</td>
                <td>{{ student.age }}</td>
                <td>{{ student.course }}</td>
                <td>
                    {% if student.summary %}
                    <a href="{{ student.summary.url }}">Download</a>
                    {% endif %}
                </td>
                {% if user.is_authenticated %}
                <td>
                    <a type="button" class="btn btn-danger" href="{% url 'students:delete' pk=student.id %}">Delete</a>
                </td>
                <td>
                    <a type="button" class="btn btn-success" href="{% url 'students:update' pk=student.id %}">Update</a>
                </td>
                {% endif %}
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

lms/students/templates/students_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <br>
            <input class="btn btn-info" type="submit" value="Update"/>
        </form>
    </div>
{% endblock %}